# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bab70c40f8716a38ac76f6908b9a7e3b2972abb4c505a3a0678b7b52ea6278b4868a37761ce70092a64b5daf57478d39eb2fe97b2a43042de538a3d9a5671d4

test:
  secret_key_base: f69409fac28b6453978146863073b848b53b6b2c2ae73ff23708fc952801ff050af25707c62ef7b85c7c98d0c9317838deb76013517990425ed9fecd4c4c72c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
